#!/usr/bin/env python3
"""Resolve the newest release of every pinned image.

Used by the weekly at-latest CI job. Writes an images.env-shaped file
with the newest versions (by tag and digest) and a Markdown table of
pinned vs latest, so a failing run can open an issue that says
exactly what moved.

    resolve_latest.py --env-out images.latest.env --md-out diff.md

Standard library only. Set GITHUB_TOKEN to lift the GitHub API rate
limit; no other credential is used.
"""
import argparse
import json
import os
import pathlib
import re
import urllib.request

BOOK = pathlib.Path(__file__).resolve().parent.parent
UA = {"User-Agent": "the-ai-engineers-library-examples"}


def get(url, headers=None, method="GET"):
    req = urllib.request.Request(url, headers={**UA, **(headers or {})},
                                 method=method)
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.headers, r.read()


def gh(path):
    h = {"Accept": "application/vnd.github+json"}
    if os.environ.get("GITHUB_TOKEN"):
        h["Authorization"] = f"Bearer {os.environ['GITHUB_TOKEN']}"
    return json.loads(get(f"https://api.github.com/{path}", h)[1])


def latest_semver_release(repo):
    """Highest non-draft, non-prerelease release tagged vX.Y.Z.
    Highest, not newest: projects ship patches to older branches."""
    tags = [rel["tag_name"]
            for rel in gh(f"repos/{repo}/releases?per_page=100")
            if not rel["draft"] and not rel["prerelease"]
            and re.fullmatch(r"v\d+\.\d+\.\d+", rel["tag_name"])]
    if not tags:
        raise SystemExit(f"no vX.Y.Z release found for {repo}")
    return max(tags, key=lambda t: tuple(map(int, t[1:].split("."))))


def pypi_latest(name):
    return json.loads(get(f"https://pypi.org/pypi/{name}/json")[1])[
        "info"]["version"]


def digest(image, tag):
    """Index digest of image:tag, via the registry's anonymous API."""
    if image.startswith("ghcr.io/"):
        repo = image[len("ghcr.io/"):]
        tok_url = f"https://ghcr.io/token?scope=repository:{repo}:pull"
        base = "https://ghcr.io"
    else:
        repo = image if "/" in image else f"library/{image}"
        tok_url = ("https://auth.docker.io/token?service=registry."
                   f"docker.io&scope=repository:{repo}:pull")
        base = "https://registry-1.docker.io"
    token = json.loads(get(tok_url)[1])["token"]
    accept = ", ".join([
        "application/vnd.oci.image.index.v1+json",
        "application/vnd.docker.distribution.manifest.list.v2+json",
        "application/vnd.oci.image.manifest.v1+json",
        "application/vnd.docker.distribution.manifest.v2+json"])
    headers, _ = get(f"{base}/v2/{repo}/manifests/{tag}",
                     {"Authorization": f"Bearer {token}",
                      "Accept": accept}, method="HEAD")
    return headers["Docker-Content-Digest"]


def read_env(path):
    out = {}
    for line in pathlib.Path(path).read_text().splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--env-out", required=True)
    p.add_argument("--md-out", required=True)
    args = p.parse_args()

    llama = latest_semver_release("ggml-org/llama.cpp")
    vllm = latest_semver_release("vllm-project/vllm")
    prom = latest_semver_release("prometheus/prometheus")
    graf = latest_semver_release("grafana/grafana")
    guide = "v" + pypi_latest("guidellm")

    latest = {
        "LLAMA_CPP_IMAGE": ("ghcr.io/ggml-org/llama.cpp",
                            f"server-{llama}"),
        "VLLM_CPU_IMAGE": ("vllm/vllm-openai-cpu", vllm),
        "GUIDELLM_IMAGE": ("ghcr.io/vllm-project/guidellm", guide),
        "PROMETHEUS_IMAGE": ("prom/prometheus", prom),
        "GRAFANA_IMAGE": ("grafana/grafana", graf.lstrip("v")),
    }
    pinned = read_env(BOOK / "images.env")
    env_lines = ["# Generated by scripts/resolve_latest.py. Not a pin."]
    md = ["| Image | Pinned | Latest | Moved |", "|---|---|---|---|"]
    for key, (image, tag) in latest.items():
        ref = f"{image}:{tag}@{digest(image, tag)}"
        env_lines.append(f"{key}={ref}")
        old = pinned.get(key, "")
        old_tag = old.split("@")[0].rsplit(":", 1)[-1]
        md.append(f"| `{image}` | `{old_tag}` | `{tag}` | "
                  f"{'no' if old == ref else 'yes'} |")
        print(f"{key}: {old_tag} -> {tag}")
    pathlib.Path(args.env_out).write_text("\n".join(env_lines) + "\n")
    pathlib.Path(args.md_out).write_text("\n".join(md) + "\n")


if __name__ == "__main__":
    main()
